name:  Python Check
"on":
   push:
   branches:
   - mani
   jobs:
   check:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses:
  actions/checkout@v4
      - name: Setup Python
        uses:
  action/setup-python@5
        with:
          python-version:
  "3.11"
       - name: Check Python
         run:python
  --version       

      
