name: python check
on:
push:
branches:{main}
pull_request:
branches:{mani}
jobs:
check:
runs-on:ubuntu-latest
step:
- name:checkout code 
uses:
actions/checkout@v4
-name:set up python
uses:
actions/setup-python@v5
with:
python-version:
"3.11"
-name:check python
files
run:python:-m
py_compile app.py chatbot.py 
run:python-m
py_
